#!/bin/bash

FOODS=foods.txt
 
# total number of foods
total=`cat $FOODS | wc -l` 
 
# while loop to generate random words  
# number of random generated words depends on supplied argument 
output=""
random_number=`od -N3 -An -i /dev/urandom | \
    awk -v f=0 -v r="$total" '{printf "%i\n", f + r * $1 / 16777216}'`

output="`sed $random_number"q;d" $FOODS`"
echo $output
